### ISSUE TITLE
Dugway not working; Can't get it to run

### ISSUE THREAD

**Issue by themefiend** [bigcartel/dugway#163]
I'm trying to use Dugway for Big Cartel theme development. I've been able to download / install the files from Github and get the build tool to run. However, when I type 'dugway server' or 'dugway serve' in the terminal, I keep on getting errors. When visiting the server url (127.0.0.1:9292) I get a 'This site can't be reached' message.

At first I was getting errors in the terminal about 'Fixnum' and 'Bignum' being depreciated. I manually went into the Ruby files that had the depreciated Bignum syntax and changed it to the updated version. The 'Bignum' error went away after doing so, but I still continue to get an error about 'Bad file descriptor'.

I'm not familiar with Ruby, so I'm not really sure how to solve any of these issues. I viewed several threads on Stackoverflow about the issue and tried the recommendations about updating Eventmachine and outdated Ruby gems. I also tried reinstalling Ruby. None of these issue solved the problem.

[Here's the video showing the errors I'm running into](https://vimeo.com/314144579). My OS is Windows 10.

**Comment by nickendle** [comment]
@themefiend the errors are pretty hard to see in a video, would you mind pasting them here to make it easier to troubleshoot?

**Comment by themefiend** [comment]
Hey Nick,
Here's the errors I'm getting after typing 'dugway server' in the terminal (same errors occur when typing 'dugway serve' as well:
====================

C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thin-1.5.1/lib/thin/server.rb:104: warning: constant ::Fixnum is deprecated
>> Thin web server (v1.5.1 codename Straight Razor)
>> Maximum connections set to 1024
>> Listening on 127.0.0.1:9292, CTRL+C to stop
Traceback (most recent call last):
        28: from C:/Ruby26-x64/bin/dugway:23:in `<main>'
        27: from C:/Ruby26-x64/bin/dugway:23:in `load'
        26: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/dugway-0.11.1/bin/dugway:7:in `<top (required)>'
        25: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.17.0/lib/thor/base.rb:434:in `start'
        24: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.17.0/lib/thor.rb:344:in `dispatch'
        23: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.17.0/lib/thor/invocation.rb:120:in `invoke_task'
        22: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.17.0/lib/thor/task.rb:27:in `run'
        21: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.17.0/lib/thor.rb:32:in `block in register'
        20: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.17.0/lib/thor/invocation.rb:109:in `invoke'
        19: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.17.0/lib/thor/group.rb:238:in `dispatch'
        18: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `invoke_all'
        17: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `map'
        16: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `each'
        15: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `block in invoke_all'
        14: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.17.0/lib/thor/invocation.rb:120:in `invoke_task'
        13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.17.0/lib/thor/task.rb:27:in `run'
        12: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/dugway-0.11.1/lib/dugway/cli/server.rb:25:in `start'
        11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rack-1.4.7/lib/rack/server.rb:137:in `start'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rack-1.4.7/lib/rack/server.rb:268:in `start'
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rack-1.4.7/lib/rack/handler/thin.rb:13:in `run'
         8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thin-1.5.1/lib/thin/server.rb:159:in `start'
         7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thin-1.5.1/lib/thin/backends/base.rb:63:in `start'
         6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/eventmachine.rb:196:in `run'
         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:144:in `run_machine'
         4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:547:in `run'
         3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:547:in `loop'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:553:in `block in run'
         1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:595:in `crank_selectables'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:595:in `select': Bad file descriptor (Errno::EBADF)
        28: from C:/Ruby26-x64/bin/dugway:23:in `<main>'
        27: from C:/Ruby26-x64/bin/dugway:23:in `load'
        26: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/dugway-0.11.1/bin/dugway:7:in `<top (required)>'
        25: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.17.0/lib/thor/base.rb:434:in `start'
        24: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.17.0/lib/thor.rb:344:in `dispatch'
        23: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.17.0/lib/thor/invocation.rb:120:in `invoke_task'
        22: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.17.0/lib/thor/task.rb:27:in `run'
        21: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.17.0/lib/thor.rb:32:in `block in register'
        20: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.17.0/lib/thor/invocation.rb:109:in `invoke'
        19: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.17.0/lib/thor/group.rb:238:in `dispatch'
        18: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `invoke_all'
        17: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `map'
        16: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `each'
        15: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `block in invoke_all'
        14: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.17.0/lib/thor/invocation.rb:120:in `invoke_task'
        13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.17.0/lib/thor/task.rb:27:in `run'
        12: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/dugway-0.11.1/lib/dugway/cli/server.rb:25:in `start'
        11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rack-1.4.7/lib/rack/server.rb:137:in `start'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rack-1.4.7/lib/rack/server.rb:268:in `start'
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rack-1.4.7/lib/rack/handler/thin.rb:13:in `run'
         8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thin-1.5.1/lib/thin/server.rb:159:in `start'
         7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thin-1.5.1/lib/thin/backends/base.rb:63:in `start'
         6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/eventmachine.rb:196:in `run'
         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:144:in `run_machine'
         4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:562:in `run'
         3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:559:in `ensure in run'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:559:in `each'
         1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:559:in `block in run'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:559:in `close': Bad file descriptor (Errno::EBADF)

**Comment by brettchalupa** [comment]
I think I know what's up with this. I'm going to investigate and try to fix it this week. Thanks for your patience @themefiend.

**Comment by brettchalupa** [comment]
@themefiend I believe I found the solution for this. Would you try running:

```
gem uninstall eventmachine
gem install --platform ruby eventmachine
```

The problem is that on Windows that gem runs into some trouble with `dugway server`. So by specifying the platform, it'll work.

**Comment by yankscally** [comment]
after searching around a bit, this is what I found, I'm unable to get dugway to run and I get the same errors. I also tried reinstalling eventmachine, and some other libraries.

I've had nothing but trouble getting dugway to build. I was able to create `mytheme` , however, I'm not able to run the dugway server.
