### ISSUE TITLE
unable to run dugway server on windows 10

### ISSUE THREAD

**Issue by yankscally** [bigcartel/dugway#199]
```
C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- 2.7/rubyeventmachine (LoadError)
        40: from C:/Ruby27-x64/bin/dugway:23:in `<main>'
        39: from C:/Ruby27-x64/bin/dugway:23:in `load'
        38: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/dugway-1.0.8/bin/dugway:7:in `<top (required)>'
        37: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        36: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        35: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        34: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        33: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor.rb:40:in `block in register'
        32: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
        31: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/group.rb:232:in `dispatch'
        30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `invoke_all'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `map'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `each'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `block in invoke_all'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/dugway-1.0.8/lib/dugway/cli/server.rb:25:in `start'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/server.rb:137:in `start'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/server.rb:268:in `start'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/server.rb:272:in `server'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `get'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `inject'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `each'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `block in get'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `const_get'
        15: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        14: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler/thin.rb:1:in `<top (required)>'
        12: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        11: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thin-1.8.2/lib/thin.rb:7:in `<top (required)>'
         9: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
         8: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `rescue in require'
         7: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `require'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/eventmachine.rb:8:in `<top (required)>'
         5: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
         4: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `rescue in require'
         3: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `require'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/rubyeventmachine.rb:2:in `<top (required)>'
         1: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- 2.7/rubyeventmachine (LoadError)
```

I've not been able to get dugway working at all. I am trying to build a website for a client and I have had some trouble with it, tried reinstalling ruby and doing my best to follow the errors. I'm familiar with python so I was quick to pickup how `gem` works and I was able to get dugway installed, and I was able to create a theme, but I'm not able to run the server and actually view this theme.

Any help would be very appriciated.

**Comment by yankscally** [comment]
```
PS C:\nil00151.github.io\theme\mytheme> gem uninstall eventmachine

You have requested to uninstall the gem:
        eventmachine-1.2.7-x64-mingw32

thin-1.8.2 depends on eventmachine (~> 1.0, >= 1.0.4)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]  y
Successfully uninstalled eventmachine-1.2.7-x64-mingw32
PS C:\nil00151.github.io\theme\mytheme> gem install eventmachine
Fetching eventmachine-1.2.7-x64-mingw32.gem
Successfully installed eventmachine-1.2.7-x64-mingw32
Parsing documentation for eventmachine-1.2.7-x64-mingw32
Installing ri documentation for eventmachine-1.2.7-x64-mingw32
Done installing documentation for eventmachine after 3 seconds
1 gem installed
PS C:\nil00151.github.io\theme\mytheme> dugway server --debug --verbose
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Traceback (most recent call last):
        38: from C:/Ruby27-x64/bin/dugway:23:in `<main>'
        37: from C:/Ruby27-x64/bin/dugway:23:in `load'
        36: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/dugway-1.0.8/bin/dugway:7:in `<top (required)>'
        35: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        34: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        33: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        32: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        31: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor.rb:40:in `block in register'
        30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/group.rb:232:in `dispatch'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `invoke_all'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `map'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `each'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `block in invoke_all'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/dugway-1.0.8/lib/dugway/cli/server.rb:25:in `start'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/server.rb:137:in `start'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/server.rb:268:in `start'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/server.rb:272:in `server'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `get'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `inject'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `each'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `block in get'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `const_get'
        13: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        12: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler/thin.rb:1:in `<top (required)>'
        10: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         9: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thin-1.8.2/lib/thin.rb:7:in `<top (required)>'
         7: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         6: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/eventmachine.rb:8:in `<top (required)>'
         4: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         3: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/rubyeventmachine.rb:2:in `<top (required)>'
         1: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- 2.7/rubyeventmachine (LoadError)
        39: from C:/Ruby27-x64/bin/dugway:23:in `<main>'
        38: from C:/Ruby27-x64/bin/dugway:23:in `load'
        37: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/dugway-1.0.8/bin/dugway:7:in `<top (required)>'
        36: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        35: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        34: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        33: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        32: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor.rb:40:in `block in register'
        31: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
        30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/group.rb:232:in `dispatch'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `invoke_all'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `map'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `each'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `block in invoke_all'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/dugway-1.0.8/lib/dugway/cli/server.rb:25:in `start'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/server.rb:137:in `start'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/server.rb:268:in `start'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/server.rb:272:in `server'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `get'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `inject'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `each'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `block in get'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `const_get'
        14: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        13: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler/thin.rb:1:in `<top (required)>'
        11: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        10: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thin-1.8.2/lib/thin.rb:7:in `<top (required)>'
         8: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         7: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/eventmachine.rb:8:in `<top (required)>'
         5: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
         4: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `rescue in require'
         3: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `require'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/rubyeventmachine.rb:2:in `<top (required)>'
         1: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- 2.7/rubyeventmachine (LoadError)
        39: from C:/Ruby27-x64/bin/dugway:23:in `<main>'
        38: from C:/Ruby27-x64/bin/dugway:23:in `load'
        37: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/dugway-1.0.8/bin/dugway:7:in `<top (required)>'
        36: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        35: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        34: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        33: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        32: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor.rb:40:in `block in register'
        31: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
        30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/group.rb:232:in `dispatch'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `invoke_all'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `map'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `each'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `block in invoke_all'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/dugway-1.0.8/lib/dugway/cli/server.rb:25:in `start'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/server.rb:137:in `start'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/server.rb:268:in `start'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/server.rb:272:in `server'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `get'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `inject'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `each'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `block in get'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `const_get'
        14: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        13: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler/thin.rb:1:in `<top (required)>'
        11: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        10: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thin-1.8.2/lib/thin.rb:7:in `<top (required)>'
         8: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
         7: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `rescue in require'
         6: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `require'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/eventmachine.rb:8:in `<top (required)>'
         4: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         3: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/rubyeventmachine.rb:2:in `<top (required)>'
         1: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- 2.7/rubyeventmachine (LoadError)
        40: from C:/Ruby27-x64/bin/dugway:23:in `<main>'
        39: from C:/Ruby27-x64/bin/dugway:23:in `load'
        38: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/dugway-1.0.8/bin/dugway:7:in `<top (required)>'
        37: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        36: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        35: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        34: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        33: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor.rb:40:in `block in register'
        32: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
        31: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/group.rb:232:in `dispatch'
        30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `invoke_all'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `map'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `each'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `block in invoke_all'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/dugway-1.0.8/lib/dugway/cli/server.rb:25:in `start'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/server.rb:137:in `start'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/server.rb:268:in `start'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/server.rb:272:in `server'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `get'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `inject'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `each'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `block in get'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `const_get'
        15: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        14: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-1.4.7/lib/rack/handler/thin.rb:1:in `<top (required)>'
        12: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        11: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thin-1.8.2/lib/thin.rb:7:in `<top (required)>'
         9: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
         8: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `rescue in require'
         7: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `require'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/eventmachine.rb:8:in `<top (required)>'
         5: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
         4: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `rescue in require'
         3: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `require'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/rubyeventmachine.rb:2:in `<top (required)>'
         1: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- 2.7/rubyeventmachine (LoadError)
```


in the last log I see that eventmachine library is making this error, so here I try uninstalling and reinstalling it and then I get this different, longer error message.

**Comment by yankscally** [comment]
I see your comment from issue #163 and I try the same thing, but this time with:
`gem install --platform ruby eventmachine` 

this does work!
